-- =============================================================================
-- 0004_cart_orders.sql — Carts, cart items, orders, order items
-- =============================================================================

-- --- carts -------------------------------------------------------------------
-- A cart belongs to either a logged-in user OR an anonymous session (token).
-- `email` is captured early (e.g. at checkout step 1 or newsletter) to enable
-- abandoned-cart recovery even before account creation.
create table public.carts (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references public.profiles(id) on delete cascade,
  session_token text,                                 -- anonymous identifier
  email         citext,
  status        cart_status not null default 'active',
  -- Recovery tracking
  abandoned_at  timestamptz,
  recovered_at  timestamptz,
  recovery_emails_sent int not null default 0,
  last_recovery_email_at timestamptz,
  applied_coupon_id uuid,                              -- FK added in 0007
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index carts_user_idx on public.carts(user_id);
create index carts_session_idx on public.carts(session_token);
create index carts_status_idx on public.carts(status);
-- Supports the abandoned-cart cron sweep.
create index carts_abandoned_idx on public.carts(status, abandoned_at)
  where status = 'abandoned';

create trigger carts_set_updated_at
  before update on public.carts
  for each row execute function set_updated_at();

-- --- cart_items --------------------------------------------------------------
-- `bundle_id` (nullable) records which pricing tier was chosen so AOV math and
-- the cart drawer can reconstruct savings. `unit_price_sen` is snapshotted.
create table public.cart_items (
  id            uuid primary key default gen_random_uuid(),
  cart_id       uuid not null references public.carts(id) on delete cascade,
  product_id    uuid not null references public.products(id) on delete cascade,
  bundle_id     uuid references public.bundles(id) on delete set null,
  quantity      int not null check (quantity >= 1),
  unit_price_sen int not null check (unit_price_sen >= 0),
  is_subscription boolean not null default false,
  subscription_interval subscription_interval,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (cart_id, product_id, bundle_id, is_subscription)
);

create index cart_items_cart_idx on public.cart_items(cart_id);

create trigger cart_items_set_updated_at
  before update on public.cart_items
  for each row execute function set_updated_at();

-- --- orders ------------------------------------------------------------------
-- Human-readable order number generated by a sequence (e.g. VL-100001).
create sequence if not exists order_number_seq start 100001;

create table public.orders (
  id            uuid primary key default gen_random_uuid(),
  order_number  text not null unique default ('VL-' || nextval('order_number_seq')),
  user_id       uuid references public.profiles(id) on delete set null,
  email         citext not null,
  status        order_status not null default 'pending',
  payment_status payment_status not null default 'unpaid',
  fulfillment_status fulfillment_status not null default 'unfulfilled',
  -- Monetary breakdown, all in sen.
  subtotal_sen  int not null default 0,
  discount_sen  int not null default 0,
  shipping_sen  int not null default 0,
  tax_sen       int not null default 0,
  total_sen     int not null default 0,
  loyalty_points_redeemed int not null default 0,
  loyalty_points_earned int not null default 0,
  currency      text not null default 'MYR',
  -- Attribution (for CAC / channel analytics).
  utm_source    text,
  utm_medium    text,
  utm_campaign  text,
  -- Linkages
  coupon_id     uuid,                                  -- FK added in 0007
  subscription_id uuid,                                -- FK added in 0006
  cart_id       uuid references public.carts(id) on delete set null,
  -- Stripe
  stripe_checkout_session_id text,
  stripe_payment_intent_id   text,
  -- Address snapshots (immutable copy at purchase time).
  shipping_address jsonb,
  billing_address  jsonb,
  -- Fulfillment
  tracking_number text,
  tracking_url    text,
  notes         text,
  placed_at     timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index orders_user_idx on public.orders(user_id);
create index orders_status_idx on public.orders(status);
create index orders_payment_status_idx on public.orders(payment_status);
create index orders_created_idx on public.orders(created_at);
create index orders_stripe_session_idx on public.orders(stripe_checkout_session_id);

create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function set_updated_at();

-- --- order_items -------------------------------------------------------------
-- Snapshots product name/sku/price so historical orders are stable even if the
-- catalog later changes.
create table public.order_items (
  id            uuid primary key default gen_random_uuid(),
  order_id      uuid not null references public.orders(id) on delete cascade,
  product_id    uuid references public.products(id) on delete set null,
  bundle_id     uuid references public.bundles(id) on delete set null,
  product_name  text not null,
  product_sku   text,
  quantity      int not null check (quantity >= 1),
  unit_price_sen int not null check (unit_price_sen >= 0),
  total_sen     int not null check (total_sen >= 0),
  is_subscription boolean not null default false,
  created_at    timestamptz not null default now()
);

create index order_items_order_idx on public.order_items(order_id);
create index order_items_product_idx on public.order_items(product_id);
