-- =============================================================================
-- 0007_coupons.sql — Coupons / discount codes + redemptions
-- =============================================================================

create table public.coupons (
  id            uuid primary key default gen_random_uuid(),
  code          citext not null unique,
  description   text,
  discount_type discount_type not null,
  -- For 'percentage': 0-100. For 'fixed_amount': value in sen. Ignored for
  -- 'free_shipping'.
  discount_value int not null default 0,
  -- Conditions
  min_order_sen int not null default 0,
  max_discount_sen int,                                -- cap for percentage coupons
  -- Usage limits
  usage_limit   int,                                   -- null = unlimited
  usage_limit_per_user int,
  times_used    int not null default 0,
  -- Scheduling
  starts_at     timestamptz,
  expires_at    timestamptz,
  is_active     boolean not null default true,
  -- Whether auto-generated by abandoned-cart flow.
  is_automatic  boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index coupons_active_idx on public.coupons(is_active);

create trigger coupons_set_updated_at
  before update on public.coupons
  for each row execute function set_updated_at();

create table public.coupon_redemptions (
  id            uuid primary key default gen_random_uuid(),
  coupon_id     uuid not null references public.coupons(id) on delete cascade,
  user_id       uuid references public.profiles(id) on delete set null,
  order_id      uuid references public.orders(id) on delete set null,
  discount_sen  int not null default 0,
  created_at    timestamptz not null default now()
);

create index coupon_redemptions_coupon_idx on public.coupon_redemptions(coupon_id);
create index coupon_redemptions_user_idx on public.coupon_redemptions(user_id);

-- Wire the deferred FKs from carts + orders now that coupons exists.
alter table public.carts
  add constraint carts_applied_coupon_id_fkey
  foreign key (applied_coupon_id) references public.coupons(id) on delete set null;

alter table public.orders
  add constraint orders_coupon_id_fkey
  foreign key (coupon_id) references public.coupons(id) on delete set null;
